### ISSUE TITLE
Implement QR Code Tracking for Hololens 2

### ISSUE THREAD

**Issue by jamsteh** [The12thAstronaut/SUITS-2021#28]
Hololens 2 Mixed Reality QR code tracking is a method to help lunar astronauts scan and identify objects/tools.
**Documentation:**
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/qr-code-tracking

![image](https://user-images.githubusercontent.com/54650706/106050718-1a319d80-60ad-11eb-94ec-0b7c64968b1c.png)

Tasks (edited by Neil)
- [ ] Test QR Sample 
- [ ] Integrate QR Sample with project
- [ ] Get a virtual cube to follow the QR code, test with webcam
- [ ] Configure QR code/integrate with UI spawning
